-- Run this script in your Oracle Database to create all necessary tables

-- 1. Students Table (For Registration and Login)
CREATE TABLE students (
    student_id VARCHAR2(50) PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    room_no VARCHAR2(20),
    password_hash VARCHAR2(255) NOT NULL,
    subscription_type VARCHAR2(50),
    role VARCHAR2(20) DEFAULT 'student'
);

-- 2. Menu Table (For Daily Meal Offerings)
CREATE TABLE menu (
    menu_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_date DATE NOT NULL,
    meal_type VARCHAR2(50) NOT NULL,
    items VARCHAR2(500) NOT NULL
);

-- 3. Attendance Table (For Tracking Meals)
CREATE TABLE attendance (
    attendance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR2(50) REFERENCES students(student_id),
    attendance_date DATE NOT NULL,
    breakfast NUMBER(1) DEFAULT 0,
    lunch NUMBER(1) DEFAULT 0,
    dinner NUMBER(1) DEFAULT 0
);

-- 4. Inventory Table (For Kitchen Stock)
CREATE TABLE inventory (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    qty NUMBER DEFAULT 0,
    unit VARCHAR2(20),
    threshold NUMBER DEFAULT 10
);

-- 5. Extra Charges Table (For Additional Items)
CREATE TABLE extra_charges (
    charge_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charge_date DATE NOT NULL,
    student_id VARCHAR2(50) REFERENCES students(student_id),
    item VARCHAR2(100) NOT NULL,
    qty NUMBER DEFAULT 1,
    amount NUMBER(10,2) NOT NULL
);

-- Insert Default Admin User
INSERT INTO students (student_id, name, room_no, password_hash, subscription_type, role) 
VALUES ('admin', 'System Admin', 'Admin', 'admin123', 'None', 'admin');

COMMIT;
